### ISSUE TITLE
Mapa Mental 3.0

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-ToniDepp#1]
![MM-3 0-EDUARDO-TOMAS](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-ToniDepp/assets/124863328/c2d4abf5-e4ab-479f-9a73-2aa7ae53696c)

**Comment by Luz1727** [comment]
20/20

**Comment by josealfredo79** [comment]
@ToniDepp Esto no puede ser un mapa mental...falta mas informacion por favor..para que se tome en cuenta... @Luz1727 favor de evaluar mas objetivo..por favor...
